"""empty message

Revision ID: 0626555fde49
Revises: 4ad68e46366c
Create Date: 2016-08-02 17:33:56.860635

"""

# revision identifiers, used by Alembic.
revision = '0626555fde49'
down_revision = '4ad68e46366c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service', sa.Column('status', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service', 'status')
    ### end Alembic commands ###
