"""empty message

Revision ID: 0e759d2f01a3
Revises: da700bbde8f3
Create Date: 2016-08-15 14:52:40.385853

"""

# revision identifiers, used by Alembic.
revision = '0e759d2f01a3'
down_revision = 'da700bbde8f3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_version',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=30), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'service', sa.Column('version_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'service', 'service_version', ['version_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'service', type_='foreignkey')
    op.drop_column(u'service', 'version_id')
    op.drop_table('service_version')
    ### end Alembic commands ###
