"""empty message

Revision ID: 107f06a9e803
Revises: e04613954bca
Create Date: 2016-10-04 14:20:07.034776

"""

# revision identifiers, used by Alembic.
revision = '107f06a9e803'
down_revision = 'e04613954bca'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_cluster',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=10), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column(u'service', sa.Column('cluster_id', sa.Integer(), nullable=True))
    op.add_column(u'service', sa.Column('iscsi_status', sa.Integer(), nullable=True))
    op.alter_column(u'service', 'ip_mac',
               existing_type=mysql.VARCHAR(length=30),
               nullable=False)
    op.create_index(op.f('ix_service_ip_mac'), 'service', ['ip_mac'], unique=False)
    op.create_foreign_key(None, 'service', 'service_cluster', ['cluster_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'service', type_='foreignkey')
    op.drop_index(op.f('ix_service_ip_mac'), table_name='service')
    op.alter_column(u'service', 'ip_mac',
               existing_type=mysql.VARCHAR(length=30),
               nullable=True)
    op.drop_column(u'service', 'iscsi_status')
    op.drop_column(u'service', 'cluster_id')
    op.drop_table('service_cluster')
    ### end Alembic commands ###
