"""empty message

Revision ID: 231ae505db55
Revises: 7a3659f18109
Create Date: 2016-10-12 16:30:28.512258

"""

# revision identifiers, used by Alembic.
revision = '231ae505db55'
down_revision = '7a3659f18109'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service', sa.Column('old_version_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'service', 'service_version', ['old_version_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'service', type_='foreignkey')
    op.drop_column('service', 'old_version_id')
    ### end Alembic commands ###
