"""empty message

Revision ID: 3e458f8c54a4
Revises: 0e759d2f01a3
Create Date: 2016-08-16 16:15:29.235675

"""

# revision identifiers, used by Alembic.
revision = '3e458f8c54a4'
down_revision = '0e759d2f01a3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_version', sa.Column('description', sa.Text(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service_version', 'description')
    ### end Alembic commands ###
