"""empty message

Revision ID: 4ad68e46366c
Revises: cee23ffa02c3
Create Date: 2016-08-02 17:29:33.499526

"""

# revision identifiers, used by Alembic.
revision = '4ad68e46366c'
down_revision = 'cee23ffa02c3'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service', 'status')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service', sa.Column('status', mysql.VARCHAR(length=10), nullable=True))
    ### end Alembic commands ###
