"""empty message

Revision ID: 7a3659f18109
Revises: a52c64e85457
Create Date: 2016-10-04 15:53:56.502029

"""

# revision identifiers, used by Alembic.
revision = '7a3659f18109'
down_revision = 'a52c64e85457'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('service', 'ip_mac',
               existing_type=mysql.VARCHAR(length=30),
               nullable=True)
    op.drop_index('ix_service_ip_mac', table_name='service')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_service_ip_mac', 'service', ['ip_mac'], unique=False)
    op.alter_column('service', 'ip_mac',
               existing_type=mysql.VARCHAR(length=30),
               nullable=False)
    ### end Alembic commands ###
