"""empty message

Revision ID: 9cf380744923
Revises: 231ae505db55
Create Date: 2016-10-12 17:58:40.709680

"""

# revision identifiers, used by Alembic.
revision = '9cf380744923'
down_revision = '231ae505db55'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'service_ibfk_3', 'service', type_='foreignkey')
    op.drop_column('service', 'old_version_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service', sa.Column('old_version_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key(u'service_ibfk_3', 'service', 'service_version', ['old_version_id'], ['id'])
    ### end Alembic commands ###
