"""empty message

Revision ID: a7748e22740b
Revises: 7a3659f18109
Create Date: 2016-10-14 15:07:01.399741

"""

# revision identifiers, used by Alembic.
revision = 'a7748e22740b'
down_revision = '7a3659f18109'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service', sa.Column('new_version_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'service', 'service_version', ['new_version_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'service', type_='foreignkey')
    op.drop_column('service', 'new_version_id')
    ### end Alembic commands ###
