"""empty message

Revision ID: b492e1cf9101
Revises: e7124aca6e22
Create Date: 2016-08-12 17:16:37.842120

"""

# revision identifiers, used by Alembic.
revision = 'b492e1cf9101'
down_revision = 'e7124aca6e22'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('update_date', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('update_ip', sa.String(length=16), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'update_ip')
    op.drop_column('users', 'update_date')
    ### end Alembic commands ###
