"""empty message

Revision ID: e04613954bca
Revises: f377a14d8a7f
Create Date: 2016-08-22 15:27:29.941388

"""

# revision identifiers, used by Alembic.
revision = 'e04613954bca'
down_revision = 'f377a14d8a7f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('machine_record', sa.Column('option_ip', sa.String(length=21), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('machine_record', 'option_ip')
    ### end Alembic commands ###
