"""empty message

Revision ID: f377a14d8a7f
Revises: 3e458f8c54a4
Create Date: 2016-08-17 18:36:56.799020

"""

# revision identifiers, used by Alembic.
revision = 'f377a14d8a7f'
down_revision = '3e458f8c54a4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('machine_record', sa.Column('create_time', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_service_ip'), 'service', ['ip'], unique=False)
    op.drop_index('index_name', table_name='service')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('index_name', 'service', ['ip'], unique=False)
    op.drop_index(op.f('ix_service_ip'), table_name='service')
    op.drop_column('machine_record', 'create_time')
    ### end Alembic commands ###
